import "./globals.css";
import AuthProvider from "./(components)/AuthProvider";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import NavBar from "./(components)/NavBar";
import { redirect } from "next/navigation";
import { Inter, Work_Sans } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const WorkSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options)
  console.log("layout", session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main className="">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
